### ISSUE TITLE
add bottom-bar synonym selector 

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/top-bar.css#1]
Random idea, but would it be handy to expose these styles as bottom-bar as well?  It would provide an additional hook for when its used on the bottom.

```css

.top-bar div { foo:bar; }
.bottom-bar div { foo:baz; }

```
